### ISSUE TITLE
Supervise multiple processes

### ISSUE THREAD

**Issue by metmajer** [darkone23/ansible-supervisor-example#1]
Hi - great project!

Is it possible to use eggsby.supervise to supervise multiple processes?

Thanks, Martin

**Comment by darkone23** [comment]
Yes @metmajer, this role will just register a new program with supervisord, so if you have multiple supervise roles like:

``` yaml
- roles:
  - role: supervise
    name: example
    command: echo 'hello world'
  - role: supervise
    name: other-example
    command: echo 'goodbye world'
```

Then you would see programs when you called `~/bin/supervisorctl status` - `example` and `other-example`.

p.s. I'm working on making this work with the latest version of ansible (1.7) - it currently only works on 1.6 and below.
